"""Create Codec For C Language."""
# coding=utf-8
#
# /************************************************************************************
# ***
# ***    Copyright 2023 Dell(18588220928@163.com), All Rights Reserved.
# ***
# ***    File Author: Dell, Sat 29 Jul 2023 09:12:59 PM CST
# ***
# ************************************************************************************/
#
# Create C/C++ codec
# python cc_codec.py | tee project/codec.h

from clip.simple_tokenizer import SimpleTokenizer
import pdb


codec = SimpleTokenizer()

def x(str):
    str = str.replace("\\", "\\" + "\\")
    str = str.replace("\"", "\\" + "\"")
    return str

def create_byte_encoder_code():
    '''
        static std::map<uint32_t, std::string> clip_text_byte_encoder {
            {33, "!"},
            {174, "®"},
        };
    '''
    print("static std::map<uint32_t, std::string> clip_text_byte_encoder {")
    for k, v in codec.byte_encoder.items():
        print(f"    {{{k}, \"{x(v)}\"}},")
    print("};")


def create_word_encoder_code():
    '''
        static std::map<std::string, uint32_t> clip_text_word_encoder {
            {"a</w>", 320},
            {"hello</w>", 3306},
            {"diagram</w>", 22697},
        };
    '''
    print("static std::map<std::string, uint32_t> clip_text_word_encoder {")
    for k, v in codec.encoder.items():
        print(f"    {{\"{x(k)}\", {v}}},")
    print("};")


def create_bpe_ranks_code():
    '''
        static std::map<std::string, uint32_t> clip_text_bpe_ranks {
            {('i', 'n'), 0},
        };
    '''
    print("static std::map<std::string, uint32_t> clip_text_bpe_ranks {")
    for k, v in codec.bpe_ranks.items():
        print(f"    {{\"{x(k[0])} {x(k[1])}\", {v}}},")
    print("};")


def create_byte_decoder_code():
    '''
        static std::map<std::string, uint32_t> clip_text_byte_decoder {
            {"!", 33},
            {"®", 174},
        };
    '''
    print("static std::map<std::string, uint32_t> clip_text_byte_decoder {")
    for k, v in codec.byte_decoder.items():
        print(f"    {{\"{x(k)}\", {v}}},")
    print("};")


def create_word_decoder_code():
    '''
        static std::map<uint32_t, std::string> clip_text_word_decoder {
            {320, "a</w>"},
            {3306, "hello</w>"},
            {22697, "diagram</w>"},
        };
    '''

    print("static std::map<uint32_t, std::string> clip_text_word_decoder {")
    for k, v in codec.decoder.items():
        print(f"    {{{k}, \"{x(v)}\"}},")
    print("};")


if __name__ == '__main__':
    print("/**********************************************************************")
    print("* Warnning: DO NOT Edit this file, it's created by cc_codec.py")
    print("**********************************************************************/")

    create_byte_encoder_code()
    create_word_encoder_code()
    create_byte_decoder_code()
    create_word_decoder_code()
    create_bpe_ranks_code()
